repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        pass_filenames: false

      - id: ruff-fix
        name: ruff check
        entry: ruff check
        language: system
        pass_filenames: false

      - id: pyright
        name: pyright
        entry: pyright
        language: system
        pass_filenames: false
