[project]
version = "0.0.1"

[project.optional-dependencies]
dev = [
    "ruff",
    "pyright",
    "pytest",
]

[tool.pyright]
useLibraryCodeForTypes = false
reportPrivateImportUsage = false
reportIncompatibleMethodOverride = false

[tool.ruff]
fix = true

[tool.ruff.lint]
ignore = [
    "E741",
]
extend-select = [
    "I",
]
